- block:
    - name: Update all packages on a Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - update

- block:
    - name: Update all packages on a CentOS/Red Hat Enterprise Linux
      yum:
        name: '*'
        state: latest
        update_only: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'  or ansible_distribution == 'Amazon'
  tags:
    - update
