- hosts: all
  become: true
  roles:
    - ../roles/update
    
- hosts: all
  become: true
  tasks:
  - name: Ensure a list of yum packages are installed
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - python-pip
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  - name: Add elastic PGP key
    shell: "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- hosts: master_node
  roles:
  - role: elastic.elasticsearch
    vars:
    es_major_version: "7.x"
    es_version: "7.7.1"
    es_data_dirs:
      - "/mnt/elasticsearch/data" # CHANGE_ME #
    es_config:
      node.name: "es-master-1"
      cluster.name: "audit-cluster"
      cluster.initial_master_nodes: "es-master-1"
      network.host: "0.0.0.0"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_heap_size: "16g" # CHANGE_ME #
    es_start_service: false

- hosts: additional_master_nodes
  roles:
  - role: elastic.elasticsearch
  vars:
    es_major_version: "7.x"
    es_version: "7.7.1"
    es_data_dirs:
      - "/mnt/elasticsearch/data" # CHANGE_ME #
    es_config:
      cluster.name: "audit-cluster"
      cluster.initial_master_nodes: "es-master-1"
      discovery.seed_hosts:  "{{ hostvars['master_node']['ansible_default_ipv4']['address'] }}:9300"
      network.host: "0.0.0.0"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_heap_size: "16g" # CHANGE_ME #
    es_start_service: false

- hosts: data_nodes
  roles:
  - role: elastic.elasticsearch
  vars:
    es_major_version: "7.x"
    es_version: "7.7.1"
    es_data_dirs:
      - "/mnt/elasticsearch/data" # CHANGE_ME #
    es_config:
      cluster.name: "audit-cluster"
      cluster.initial_master_nodes: "es-master-1"
      discovery.seed_hosts:  "{{ hostvars['master_node']['ansible_default_ipv4']['address'] }}:9300"
      network.host: "0.0.0.0"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: true
    es_heap_size: "16g" # CHANGE_ME #
    es_start_service: false

- hosts: coordinating_nodes
  roles:
  - role: elastic.elasticsearch
  vars:
    es_major_version: "7.x"
    es_version: "7.7.1"
    es_data_dirs:
      - "/mnt/elasticsearch/data" # CHANGE_ME #
    es_config:
      cluster.name: "audit-cluster"
      cluster.initial_master_nodes: "es-master-1"
      discovery.seed_hosts:  "{{ hostvars['master_node']['ansible_default_ipv4']['address'] }}:9300"
      network.host: "0.0.0.0"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: false
      bootstrap.memory_lock: true
    es_heap_size: "16g" # CHANGE_ME #
    es_start_service: false

- hosts: all
  become: true
  vars:
    mount_volume: false # CHANGE_ME #
  roles:
    - ../roles/modify_limits_bare_metal
    - ../roles/reboot
  tasks:
  - name: Make filesytem
    filesystem:
      fstype: xfs
      dev: /dev/nvme1n1
    when: mount_volume | default(false) | bool == true
  - name: Create elasticsearch directory
    file: 
      path: /mnt/elasticsearch # CHANGE_ME #
      owner: elasticsearch
      group: elasticsearch
      mode: 0755 
      state: directory
    when: mount_volume | default(false) | bool == true
  - name: Mount volume
    command: "mount -o discard /dev/nvme1n1 /mnt/elasticsearch/"
    when: mount_volume | default(false) | bool == true
  - name: Create data directory
    file: 
      path: /mnt/elasticsearch/data # CHANGE_ME #
      owner: elasticsearch
      group: elasticsearch
      mode: 0755 
      state: directory
  - name: Start elasticsearch
    service:
      name: elasticsearch
      state: started

- hosts: data_nodes
  become: yes
  tasks:
  - copy:
      src: ../config-files/logstash/logstash.repo
      dest: /etc/yum.repos.d/logstash.repo
  - name: Remove old logstash version
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - logstash

  - name: Install logstash
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - java
      - logstash-7.7.1
  - copy:
      src: ../config-files/logstash/logstash.yml
      dest: /etc/logstash/logstash.yml
  - copy:
      src: ../config-files/logstash/jvm.options
      dest: /etc/logstash/jvm.options
  - copy:
      src: ../config-files/logstash/audit-pipeline.conf
      dest: /etc/logstash/conf.d/audit-pipeline.conf
  - name: Add ec2 user
    lineinfile: 
      dest: /etc/logstash/startup.options
      regexp: '^(.*)LS_USER(.*)$' 
      line: LS_USER=ec2-user
      backrefs: yes
  - name: Add ec2 group
    lineinfile: 
      dest: /etc/logstash/startup.options
      regexp: '^(.*)LS_GROUP(.*)$' 
      line: LS_GROUP=ec2-user
      backrefs: yes
  - name: Start logstash
    shell: "sudo service logstash start"

- hosts: master_node
  become: yes
  tasks:
  - copy:
      src: ../config-files/kibana/kibana.repo
      dest: /etc/yum.repos.d/kibana.repo
  - name: Remove old kibana version
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - kibana
  - name: Install kibana
    yum:
      name: "{{ packages }}"
      state: "installed"
      update_cache: yes
    vars:
      packages:
      - kibana-7.7.1
  - copy:
      src: ../config-files/kibana/kibana.yml
      dest: /etc/kibana/kibana.yml
  - name: Start kibana
    shell: "sudo systemctl start kibana.service"
    
