- name: Setup kubeconfig for "{{username }}" user
  command: "{{ item }}"
  with_items:
  - mkdir -p /home/"{{username }}"/.kube
  - cp -i /etc/kubernetes/admin.conf /home/"{{username }}"/.kube/config
  - chown {{username }}:{{username }} /home/"{{username }}"/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
